### ISSUE TITLE
Go2Rtc

### ISSUE THREAD

**Issue by Calcu2006** [Anonym-tsk/MMM-HomeAssistant-WebRTC#6]
Hi all,
Just to know if anybody made this module to work with go2rtc

It works with rtsptoweb and webrtc card 2.x, but no with the upgraded card to 3.x an go2rtc.

Any possibility?

Thanks in advance

**Comment by Anonym-tsk** [comment]
Use https://github.com/Anonym-tsk/MMM-go2rtc
